// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHSmhSXnjzLK5SaANbQtkhQRN8S5iW-_s',
    appId: '1:162411159854:web:001a8b44795e4c3fb85abf',
    messagingSenderId: '162411159854',
    projectId: 'first-fb-project-88093',
    authDomain: 'first-fb-project-88093.firebaseapp.com',
    storageBucket: 'first-fb-project-88093.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJXq7MhKMwJp9SJX8iPgiGH4hQEErR5ms',
    appId: '1:162411159854:android:139081bbfdba5efcb85abf',
    messagingSenderId: '162411159854',
    projectId: 'first-fb-project-88093',
    storageBucket: 'first-fb-project-88093.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsftT5wdO0N6EcZLlnVnzZ0WV43ljgKNk',
    appId: '1:162411159854:ios:2bc9923cffab918db85abf',
    messagingSenderId: '162411159854',
    projectId: 'first-fb-project-88093',
    storageBucket: 'first-fb-project-88093.firebasestorage.app',
    iosBundleId: 'com.example.fashionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsftT5wdO0N6EcZLlnVnzZ0WV43ljgKNk',
    appId: '1:162411159854:ios:2bc9923cffab918db85abf',
    messagingSenderId: '162411159854',
    projectId: 'first-fb-project-88093',
    storageBucket: 'first-fb-project-88093.firebasestorage.app',
    iosBundleId: 'com.example.fashionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHSmhSXnjzLK5SaANbQtkhQRN8S5iW-_s',
    appId: '1:162411159854:web:03191e4e6aea5fc5b85abf',
    messagingSenderId: '162411159854',
    projectId: 'first-fb-project-88093',
    authDomain: 'first-fb-project-88093.firebaseapp.com',
    storageBucket: 'first-fb-project-88093.firebasestorage.app',
  );
}
